jobs:
  - name: testdup2mani
    type: manifest
    steps:
      - IN: image1
       # versionNumber: 01234
     # - IN: t111     

  - name: test-runSh-webhookv2
    type: runSh
    #runtime:
    #  architecture: aarch64
    #  os: Ubuntu_16.04
     # container: true  #default
    on_start:
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    steps:
      #- IN: notify-slack
     # - IN: langtest_u14golall
      - OUT: trigger
      - OUT: state
      - OUT: filejfrog
      - OUT: cliconfig
      - OUT: sample_php_ciRepo
      - OUT: allpl-release11
      - OUT: my_hipchat_key
     # - OUT: slackIN
      - OUT: scriptphprepo
      - OUT: image1
      - OUT: testdup2mani
      #- OUT: twoRunsh
      - OUT: kube-dockeropts
      - OUT: test-trigger
      - OUT: test_params
      - OUT: allpl-lb
      - OUT: allpl-scale2
      #- IN: script3
      - OUT: allpl-version
   #   - IN: testintegrationwebhook
      - TASK:  
        - script: echo "---integration typed resource---"
        - script: echo "int name ------->-"$TESTINTEGRATIONWEBHOOK_NAME
        - script: echo "webhookurl ------->-"$TESTINTEGRATIONWEBHOOK_INTEGRATION_WEBHOOKURL
        - script: echo "authorization ------->---"$TESTINTEGRATIONWEBHOOK_INTEGRATION_AUTHORIZATION
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    on_cancel:
      - script: echo "This works on_always"
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
      
  - name: sampleRunsh
    type: runSh
    steps:
      - IN: script3repo
      - TASK:  
        - script: ./IN/script3repo/gitRepo/echo.sh          
      
  - name: twoRunsh
    type: runSh
   # runtime:
   #   architecture: x86_64
   #   os: Ubuntu_16.04
    #  container: true  #default
    steps:
      - IN: trigger
      - IN: state
      - IN: filejfrog
      - IN: cliconfig
      - IN: sample_php_ciRepo
      - IN: allpl-release11
      - IN: my_hipchat_key
     # - OUT: slackIN
      - IN: scriptphprepo
      - IN: image1
      - IN: testdup2mani
      - IN: test-runSh-webhookv2
      - IN: kube-dockeropts
      - IN: test-trigger
      - IN: test_params
      - IN: allpl-lb
      - IN: allpl-scale2
     # - IN: script3
      - IN: allpl-version
    
   #   - IN: testintegrationwebhook
      - TASK:  
        - script: ./IN/scriptphprepo/gitRepo/echo.sh
        - script: echo "test script is showing"
        
  - name: allpl-release11
    type: release
    steps:
      - IN: allpl-version
    
         #versionName: testrelease
      - TASK: managed
        bump: beta
   
